# Generated by Django 5.2.6 on 2025-09-04 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(blank=True, default='Unknown', max_length=255, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('face_thumbnail', models.ImageField(upload_to='thumbnails/%Y/%m/%d/')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_persons', to='core.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='TimestampLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('detected_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to='core.detectedperson')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='core.mediafile')),
            ],
        ),
    ]
