# Generated by Django 5.2.6 on 2025-11-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_video_audiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedperson',
            name='arcface_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectedperson',
            name='facenet_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='annotated_video',
            field=models.FileField(blank=True, null=True, upload_to='results/annotated/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('saved', 'Saved'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
