# Generated by Django 5.2.6 on 2025-11-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detectedperson_arcface_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('saved', 'Saved'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
    ]
