# Generated by Django 5.2.6 on 2025-11-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mediafile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='video_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
